apiVersion: skaffold/v2beta6
kind: Config
deploy:
  helm:
    releases:
      - name: nats
        chartPath: .\infra\helm\
        valuesFiles:
          - .\infra\helm\nats-values.yaml
      - name: auth
        chartPath: .\infra\helm\
        valuesFiles:
          - .\infra\helm\auth-values.yaml
        artifactOverrides:
          image: cubrenig/pgwasauth
        setValues:
      - name: email
        chartPath: .\infra\helm\
        valuesFiles:
          - .\infra\helm\email-values.yaml
        artifactOverrides:
          image: cubrenig/pgwasemail

build:
  local:
    push: false
    concurrency: 5
  artifacts:
    - image: cubrenig/pgwasauth
      context: auth_service #folder
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cubrenig/pgwasemail
      context: email_service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
